###
GET http://localhost:8080/api/rent/getbyid/1/sendconfirmation/it200269

###
POST http://localhost:8080/api/devicetype/create/light

{"watts": 40, "name": "testo", "rgb": true, "variable_temperature":false}