services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgresdb
      - POSTGRES_USER=camconnect
      - POSTGRES_DB=camconnect
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "camconnect" ]
  backend:
    container_name: backend
    image: ghcr.io/elyanuki/camconnect-backend:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - FRONTEND_URL=http://localhost:4200
      - EMAIL_PASSWORD=hHl49vc2dLvmJU27EfRY
    healthcheck:
      test: curl -f http://localhost:8080/api/q/health
  web:
    container_name: web
    image: ghcr.io/elyanuki/camconnect-web:latest
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 4200:80
volumes:
  postgres: