
###
// Teacher
POST http://localhost:8080/teacher/create

{"firstname": "Aiden", "lastname": "Smith", "password": "1234", "user_id": "it100069", "verification": ""}

###
POST http://localhost:8080/teacher/create

{"firstname": "Emma", "lastname": "Johnson", "password": "1234", "user_id": "it100070", "verification": ""}

###
POST http://localhost:8080/teacher/create

{"firstname": "Liam", "lastname": "Brown", "password": "1234", "user_id": "it100071", "verification": ""}

###
POST http://localhost:8080/teacher/create

{"firstname": "Olivia", "lastname": "Davis", "password": "1234", "user_id": "it100072", "verification": ""}

###
POST http://localhost:8080/teacher/create

{"firstname": "James", "lastname": "Wilson", "password": "1234", "user_id": "it100073", "verification": ""}



###
// Device
POST http://localhost:8080/device/create

{"height": 25.25, "dtype": "Camera", "head": "", "note": "Passt", "serial": "Sony"}

###
POST http://localhost:8080/device/create

{"height": 30.30, "dtype": "Stativ", "head": "", "note": "Mangelhaft", "serial": "Manfrotto"}

###
POST http://localhost:8080/device/create

{"height": 20.00, "dtype": "Microphone", "head": "", "note": "Kaputt", "serial": "Shure"}

###
POST http://localhost:8080/device/create

{"height": 28.10, "dtype": "Camera", "head": "", "note": "Passt", "serial": "Canon"}

###
POST http://localhost:8080/device/create

{"height": 22.15, "dtype": "Stativ", "head": "", "note": "Mangelhaft", "serial": "Gitzo"}

###
POST http://localhost:8080/device/create

{"height": 15.15, "dtype": "Microphone", "head": "", "note": "Kaputt", "serial": "Rode"}

###
POST http://localhost:8080/device/create

{"height": 26.15, "dtype": "Camera", "head": "", "note": "Passt", "serial": "Nikon"}

###
POST http://localhost:8080/device/create

{"height": 32.15, "dtype": "Stativ", "head": "", "note": "Mangelhaft", "serial": "Sachtler"}

###
POST http://localhost:8080/device/create

{"height": 18.00, "dtype": "Microphone", "head": "", "note": "Kaputt", "serial": "Audio-Technica"}

###
POST http://localhost:8080/device/create

{"height": 24.00, "dtype": "Camera", "head": "", "note": "Passt", "serial": "Panasonic"}

###
POST http://localhost:8080/device/create

{"height": 29.00, "dtype": "Stativ", "head": "", "note": "Mangelhaft", "serial": "Benro"}

###
POST http://localhost:8080/device/create

{"height": 19.00, "dtype": "Microphone", "head": "", "note": "Kaputt", "serial": "Sennheiser"}

###
POST http://localhost:8080/device/create

{"height": 27.00, "dtype": "Camera", "head": "", "note": "Passt", "serial": "Fujifilm"}

###
POST http://localhost:8080/device/create

{"height": 31.15, "dtype": "Stativ", "head": "", "note": "Mangelhaft", "serial": "Vinten"}

###
POST http://localhost:8080/device/create

{"height": 16.50, "dtype": "Microphone", "head": "", "note": "Kaputt", "serial": "Zoom"}

###
POST http://localhost:8080/device/create

{"height": 23.45, "dtype": "Camera", "head": "", "note": "Passt", "serial": "Olympus"}

###
POST http://localhost:8080/device/create

{"height": 35.23, "dtype": "Stativ", "head": "", "note": "Mangelhaft", "serial": "Libec"}

###
POST http://localhost:8080/device/create

{"height": 17.65, "dtype": "Microphone", "head": "", "note": "Kaputt", "serial": "Blue Microphones"}

###
POST http://localhost:8080/device/create

{"height": 33.5, "dtype": "Camera", "head": "", "note": "Passt", "serial": "Leica"}

###
POST http://localhost:8080/device/create

{"height": 21.23, "dtype": "Stativ", "head": "", "note": "Mangelhaft", "serial": "Vanguard"}

###
POST http://localhost:8080/device/create

{"height": 14.75, "dtype": "Microphone", "head": "", "note": "Kaputt", "serial": "Samson"}


###
// Rent
POST http://localhost:8080/rent/create

{"student_id": 12, "rent_start": "2023-11-08", "rent_end_planned": "2023-11-10", "rent_end_actual": "2023-11-15"}

###
POST http://localhost:8080/rent/update

{"rent_id": 1, "device_id": 4, "teacher_id": 3, "student_id": 12, "rent_start": "2023-11-08", "rent_end_planned": "2023-11-10", "rent_end_actual": "2023-11-15"}

###
POST http://localhost:8080/rent/create

{"student_id": 8, "rent_start": "2023-11-17", "rent_end_planned": "2023-11-20", "rent_end_actual": "2023-11-25"}

###
POST http://localhost:8080/rent/update

{"rent_id": 2, "device_id": 9, "teacher_id": 2, "student_id": 8, "rent_start": "2023-11-17", "rent_end_planned": "2023-11-20", "rent_end_actual": "2023-11-25"}

###
POST http://localhost:8080/rent/create

{"student_id": 19, "rent_start": "2023-12-03", "rent_end_planned": "2023-12-07", "rent_end_actual": "2023-12-12"}

###
POST http://localhost:8080/rent/update

{"rent_id": 3, "device_id": 7, "teacher_id": 5, "student_id": 19, "rent_start": "2023-12-03", "rent_end_planned": "2023-12-07", "rent_end_actual": "2023-12-12"}

###
POST http://localhost:8080/rent/create

{"student_id": 11, "rent_start": "2023-12-15", "rent_end_planned": "2023-12-18", "rent_end_actual": "2023-12-23"}

###
POST http://localhost:8080/rent/update

{"rent_id": 4, "device_id": 16, "teacher_id": 4, "student_id": 11, "rent_start": "2023-12-15", "rent_end_planned": "2023-12-18", "rent_end_actual": "2023-12-23"}

###
POST http://localhost:8080/rent/create

{"student_id": 14, "rent_start": "2024-01-19", "rent_end_planned": "2024-01-22", "rent_end_actual": "2024-01-27"}

###
POST http://localhost:8080/rent/update

{"rent_id": 5, "device_id": 8, "teacher_id": 2, "student_id": 14, "rent_start": "2024-01-19", "rent_end_planned": "2024-01-22", "rent_end_actual": "2024-01-27"}

###
POST http://localhost:8080/rent/create

{"student_id": 7, "rent_start": "2024-02-01", "rent_end_planned": "2024-02-04", "rent_end_actual": "2024-02-09"}

###
POST http://localhost:8080/rent/update

{"rent_id": 6, "device_id": 5, "teacher_id": 4, "student_id": 7, "rent_start": "2024-02-01", "rent_end_planned": "2024-02-04", "rent_end_actual": "2024-02-09"}

###
POST http://localhost:8080/rent/create

{"student_id": 3, "rent_start": "2024-02-13", "rent_end_planned": "2024-02-16", "rent_end_actual": "2024-02-21"}

###
POST http://localhost:8080/rent/update

{"rent_id": 7, "device_id": 11, "teacher_id": 5, "student_id": 3, "rent_start": "2024-02-13", "rent_end_planned": "2024-02-16", "rent_end_actual": "2024-02-21"}

###
POST http://localhost:8080/rent/create

{"student_id": 6, "rent_start": "2024-02-25", "rent_end_planned": "2024-02-28", "rent_end_actual": "2024-03-04"}

###
POST http://localhost:8080/rent/update

{"rent_id": 8, "device_id": 17, "teacher_id": 1, "student_id": 6, "rent_start": "2024-02-25", "rent_end_planned": "2024-02-28", "rent_end_actual": "2024-03-04"}

###
POST http://localhost:8080/rent/create

{"student_id": 18, "rent_start": "2024-03-08", "rent_end_planned": "2024-03-11", "rent_end_actual": "2024-03-16"}

###
POST http://localhost:8080/rent/update

{"rent_id": 9, "device_id": 10, "teacher_id": 3, "student_id": 18, "rent_start": "2024-03-08", "rent_end_planned": "2024-03-11", "rent_end_actual": "2024-03-16"}

###
POST http://localhost:8080/rent/create

{"student_id": 1, "rent_start": "2024-03-20", "rent_end_planned": "2024-03-23", "rent_end_actual": "2024-03-28"}

###
POST http://localhost:8080/rent/update

{"rent_id": 10, "device_id": 8, "teacher_id": 4, "student_id": 1, "rent_start": "2024-03-20", "rent_end_planned": "2024-03-23", "rent_end_actual": "2024-03-28"}

###
POST http://localhost:8080/rent/create

{"student_id": 4, "rent_start": "2024-04-01", "rent_end_planned": "2024-04-04", "rent_end_actual": "2024-04-09"}

###
POST http://localhost:8080/rent/update

{"rent_id": 11, "device_id": 6, "teacher_id": 2, "student_id": 4, "rent_start": "2024-04-01", "rent_end_planned": "2024-04-04", "rent_end_actual": "2024-04-09"}

###
POST http://localhost:8080/rent/create

{"student_id": 15, "rent_start": "2024-04-13", "rent_end_planned": "2024-04-16", "rent_end_actual": "2024-04-21"}

###
POST http://localhost:8080/rent/update

{"rent_id": 12, "device_id": 7, "teacher_id": 5, "student_id": 15, "rent_start": "2024-04-13", "rent_end_planned": "2024-04-16", "rent_end_actual": "2024-04-21"}

###
POST http://localhost:8080/rent/create

{"student_id": 2, "rent_start": "2024-04-25", "rent_end_planned": "2024-04-28", "rent_end_actual": "2024-05-03"}

###
POST http://localhost:8080/rent/update

{"rent_id": 13, "device_id": 5, "teacher_id": 1, "student_id": 2, "rent_start": "2024-04-25", "rent_end_planned": "2024-04-28", "rent_end_actual": "2024-05-03"}

###
POST http://localhost:8080/rent/create

{"student_id": 19, "rent_start": "2024-05-07", "rent_end_planned": "2024-05-10", "rent_end_actual": "2024-05-15"}

###
POST http://localhost:8080/rent/update

{"rent_id": 14, "device_id": 10, "teacher_id": 3, "student_id": 19, "rent_start": "2024-05-07", "rent_end_planned": "2024-05-10", "rent_end_actual": "2024-05-15"}

###
POST http://localhost:8080/rent/create

{"student_id": 11, "rent_start": "2024-05-19", "rent_end_planned": "2024-05-22", "rent_end_actual": "2024-05-27"}

###
POST http://localhost:8080/rent/update

{"rent_id": 15, "device_id": 12, "teacher_id": 4, "student_id": 11, "rent_start": "2024-05-19", "rent_end_planned": "2024-05-22", "rent_end_actual": "2024-05-27"}