// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'svg-cta-click': string;
}
export const cssExports: CssExports;
export default cssExports;
