# create the standard storage class for kubernetes on Docker Desktop
# only if you use docker desktop instead of minikube
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: docker.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
