# The swiss army knife for kubernetes
# We can start it as a deployment also.
# Do not forget to remove this deployment after the www-contents is copied to the volume
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knife

spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args: 
            - mkdir -p /srv/demo;
              echo "<html><head></head><body>Copy your web app to this location on this persistent volume.<br/>To the api ==> <a href="./api/user">./api/user</a></body></html>" > /srv/demo/index.html;
              tail -f /dev/null
              echo "this line is never reached. This is not a job, so delete the deployment when done with your work."
          ports:
            - containerPort: 80    
          volumeMounts:
          - name: html
            mountPath: /srv
            readOnly: false
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: nginx-www
