name: cam-connect deployment
run-name: deploying cam-connect
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'cam-connect/pom.xml' # optional
      - name: Build with Maven
        run: mvn -B package
        working-directory: backend
      - run: echo "worked"
