name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -l backend
      - name: Install java
      - uses: actions/setup-java@4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: java -version^
      - name: build backend
        working-directory: ./backend
        run: |
          mvn -B package
          
